### PR TITLE
Initial Ramen pull request

### PR DESCRIPTION
**Pull request by ryana**

### CODE REVIEW

**Comment by ryana** [comment]
Hey guys,

Any word on when there might be progress here? I have a few companies waiting on Segment.com, and they've been pretty patient, but I'd love to be able to give them a target date for when this might go live (or at least be in beta for them).

Thanks!

cc: @amillet89

**Comment by amillet89** [comment]
@ryana releasing the code to analytics.js today. still need to make a couple of UI modifications on our end to add you to the UI, should be good to go by tomorrow!

**Comment by ryana** [comment]
Wow awesome.

Is there anything I can do to help out? I never got a clear
understanding for what else I need to and/or can do around copy. Do you
need me to provide anything for the integration description page (ie.
https://segment.com/docs/integrations/ramen)

On Wednesday, June 24, 2015, amillet89 notifications@github.com wrote:

> @ryana https://github.com/ryana releasing the code to analytics.js
> today. still need to make a couple of UI modifications on our end to add
> you to the UI, should be good to go by tomorrow!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/segment-integrations/analytics.js-integration-ramen/pull/1#issuecomment-115062141
> .

## 

Ryan
508.579.7453
@angilly
Sent from Gmail Mobile

**Comment by amillet89** [comment]
hey @ryana i looked at your application, and looks like we're missing your logo (svg, tightly cropped please), and also the docs piece. you can find an example here: https://gist.github.com/amillet89/e59d2a329cd8bf1151a2. could you email those to partners@segment.com. thanks!

**Comment by ryana** [comment]
@amillet89 just sent it in. Thx!

**Comment by ryana** [comment]
Hope you all had a good wknd. Everything looking ok with what we sent in?

**Pull request merged**
